version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
  api:
    image: marketplace-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      Marketplace_db: mongodb://mongoDB/
      Marketplace_jwtPrivateKey: 'random54465445674'
      Marketplace_MP_AUTH: 'APP_USR-9999999999999999-999999-99999999999999999999999999999999-999999999'
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/share/nginx/api
  web-server:
    image: marketplace-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html